#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum gsic_interpreter_gsic_region
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	EastOntario = 472540000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	WestOntario = 472540001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	CentralOntario = 472540002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	OutsideOntario = 472540003,
}

/// <summary>
/// Status of the Interpreter
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum gsic_interpreter_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Interpreter
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum gsic_interpreter_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("gsic_interpreter")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class gsic_Interpreter : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the gsic_interpreter entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string gsic_Address = "gsic_address";
			public const string gsic_City = "gsic_city";
			public const string gsic_Country = "gsic_country";
			public const string gsic_EmailAddress = "gsic_emailaddress";
			public const string gsic_InRegistry = "gsic_inregistry";
			public const string gsic_InterpreterId = "gsic_interpreterid";
			public const string Id = "gsic_interpreterid";
			public const string gsic_InterpreterReferenceNumber = "gsic_interpreterreferencenumber";
			public const string gsic_Name = "gsic_name";
			public const string gsic_Phone = "gsic_phone";
			public const string gsic_PostalCode = "gsic_postalcode";
			public const string gsic_Province = "gsic_province";
			public const string gsic_Region = "gsic_region";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public gsic_Interpreter() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "gsic_interpreter";
	
	public const string EntityLogicalCollectionName = "gsic_interpreters";
	
	public const string EntitySetName = "gsic_interpreters";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_address")]
	public string gsic_Address
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_address");
		}
		set
		{
			this.OnPropertyChanging("gsic_Address");
			this.SetAttributeValue("gsic_address", value);
			this.OnPropertyChanged("gsic_Address");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_city")]
	public string gsic_City
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_city");
		}
		set
		{
			this.OnPropertyChanging("gsic_City");
			this.SetAttributeValue("gsic_city", value);
			this.OnPropertyChanged("gsic_City");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_country")]
	public string gsic_Country
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_country");
		}
		set
		{
			this.OnPropertyChanging("gsic_Country");
			this.SetAttributeValue("gsic_country", value);
			this.OnPropertyChanged("gsic_Country");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_emailaddress")]
	public string gsic_EmailAddress
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_emailaddress");
		}
		set
		{
			this.OnPropertyChanging("gsic_EmailAddress");
			this.SetAttributeValue("gsic_emailaddress", value);
			this.OnPropertyChanged("gsic_EmailAddress");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_inregistry")]
	public System.Nullable<bool> gsic_InRegistry
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("gsic_inregistry");
		}
		set
		{
			this.OnPropertyChanging("gsic_InRegistry");
			this.SetAttributeValue("gsic_inregistry", value);
			this.OnPropertyChanged("gsic_InRegistry");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_interpreterid")]
	public System.Nullable<System.Guid> gsic_InterpreterId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("gsic_interpreterid");
		}
		set
		{
			this.OnPropertyChanging("gsic_InterpreterId");
			this.SetAttributeValue("gsic_interpreterid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("gsic_InterpreterId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_interpreterid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.gsic_InterpreterId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_interpreterreferencenumber")]
	public string gsic_InterpreterReferenceNumber
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_interpreterreferencenumber");
		}
		set
		{
			this.OnPropertyChanging("gsic_InterpreterReferenceNumber");
			this.SetAttributeValue("gsic_interpreterreferencenumber", value);
			this.OnPropertyChanged("gsic_InterpreterReferenceNumber");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_name")]
	public string gsic_Name
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_name");
		}
		set
		{
			this.OnPropertyChanging("gsic_Name");
			this.SetAttributeValue("gsic_name", value);
			this.OnPropertyChanged("gsic_Name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_phone")]
	public string gsic_Phone
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_phone");
		}
		set
		{
			this.OnPropertyChanging("gsic_Phone");
			this.SetAttributeValue("gsic_phone", value);
			this.OnPropertyChanged("gsic_Phone");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_postalcode")]
	public string gsic_PostalCode
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_postalcode");
		}
		set
		{
			this.OnPropertyChanging("gsic_PostalCode");
			this.SetAttributeValue("gsic_postalcode", value);
			this.OnPropertyChanged("gsic_PostalCode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_province")]
	public string gsic_Province
	{
		get
		{
			return this.GetAttributeValue<string>("gsic_province");
		}
		set
		{
			this.OnPropertyChanging("gsic_Province");
			this.SetAttributeValue("gsic_province", value);
			this.OnPropertyChanged("gsic_Province");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("gsic_region")]
	public virtual gsic_interpreter_gsic_region? gsic_Region
	{
		get
		{
			return ((gsic_interpreter_gsic_region?)(EntityOptionSetEnum.GetEnum(this, "gsic_region")));
		}
		set
		{
			this.OnPropertyChanging("gsic_Region");
			this.SetAttributeValue("gsic_region", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("gsic_Region");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Interpreter
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual gsic_interpreter_statecode? statecode
	{
		get
		{
			return ((gsic_interpreter_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Interpreter
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual gsic_interpreter_statuscode? statuscode
	{
		get
		{
			return ((gsic_interpreter_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
}
#pragma warning restore CS1591
